<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>15-prerequisite-flags</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="LaunchDarkly.ServerSdk" Version="8.16.0" />
  </ItemGroup>
  <ItemGroup>
    <Content Update="wwwroot\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
