#!/usr/bin/env bash
# Copy LD_MOBILE_KEY into the gitignored Android and iOS local config files.
# Does not print the key. Does not touch sdk.dir.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ANDROID_PROPS="${SCRIPT_DIR}/android/local.properties"
IOS_XCCONFIG="${SCRIPT_DIR}/ios/LDMobileKey.xcconfig"

if [[ -z "${LD_MOBILE_KEY:-}" ]]; then
  echo "error: LD_MOBILE_KEY is required" >&2
  echo "export LD_MOBILE_KEY=\"mob-...\"  (environment mobile key, not sdk-)" >&2
  exit 1
fi

key="${LD_MOBILE_KEY}"
if [[ "$key" == sdk-* ]]; then
  echo "error: LD_MOBILE_KEY looks like a server SDK key (sdk-…). Use the mobile key (mob-…)." >&2
  exit 1
fi
if [[ "$key" != mob-* ]]; then
  echo "warning: LD_MOBILE_KEY does not start with mob-; continuing anyway." >&2
fi

write_android_properties() {
  local dest="$1"
  local tmp
  tmp="$(mktemp)"
  if [[ -f "$dest" ]]; then
    grep -v '^ld\.mobile\.key=' "$dest" > "$tmp" || true
  fi
  printf 'ld.mobile.key=%s\n' "$key" >> "$tmp"
  mv "$tmp" "$dest"
}

mkdir -p "${SCRIPT_DIR}/android" "${SCRIPT_DIR}/ios"
write_android_properties "$ANDROID_PROPS"
cat > "$IOS_XCCONFIG" <<EOF
// Generated by sync-mobile-key.sh — gitignored; do not commit.
LD_MOBILE_KEY = ${key}
EOF

echo "Wrote android/local.properties (ld.mobile.key) and ios/LDMobileKey.xcconfig."
echo "Re-run Gradle / rebuild in Xcode so BuildConfig and Info.plist pick up the key."
